version: "3"
services:
  postgres:
      image: postgres:14.1-alpine
      expose:
        - 5432
      volumes:
      - ./postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
  server:
      build: .
      depends_on:
        - postgres
      expose:
        - 1337
      ports: 
        - "1337:1337"
      environment:
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_HOST: postgres
        DATABASE_PORT: ${DATABASE_PORT}

        BOT_TOKEN: ${BOT_TOKEN}

        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}

        SERVER_PORT: ${SERVER_PORT}