export const stickers = {
  sadKlee: 'CAACAgIAAxkBAAEcyRBj3nAUiQnfRJj6aUueA6cZ8kYdewACrAsAAqf_QUgcGax9WTL6wC4E',
  kleeAndCat: 'CAACAgIAAxkBAAEcyMZj3mzsN79wou7UdGjr6wQlotqK3AAC4QsAAmmeQEgIPeEJUlAsii4E'
}

export const gifs = {
  attackedKlee: 'CgACAgIAAxkBAAMOY99TzaHcbSrZXf3t8L25WAdzcf4AAhIKAALNx0hIfzAQTcmQwdYuBA',
  jumpingKlee: 'CgACAgIAAxkBAAMPY99T1rYvj6Mo--crm9SlMrh13DgAAl0dAAIhJWhJ_LbtUoxPi-AuBA',
  waitingKlee: 'CgACAgQAAxkBAAMQY99T2TF7Tghs1VrFmPUkGMEzNE4AAgIDAAKRTxVTpzPnkHBbSmwuBA',
  flexingKlee: 'CgACAgIAAxkBAAMRY99UETayQIrohJg5r-X93qjh54UAAmgcAAKW0OFLpXtiEo8zQHcuBA',
  diyingOfCringeKlee: 'CgACAgIAAxkBAAMSY99UFdBkK4rXqA052gqOd2EBUnoAAtUTAALS7tBJQQi0lKYNBUkuBA',
  helloChatKlee: 'CgACAgQAAxkBAAMTY99UGBg3hJft30W4XE9MghLaf4kAAmcDAALvlNRTF8ioKZYN9M8uBA',
  backToBoomKlee: 'CgACAgQAAxkBAAMUY99UNcbCGPob4IKXHrOW0yw4aIcAAmUDAAKpcZRSlPITCnR-dzUuBA',
  seriousKlee: 'CgACAgQAAxkBAAMVY99URXvzidZ13nZB_39ZA8H0hvEAAwMAAkF1DFPiXA3b4nuh0C4E',
  agroKlee: 'CgACAgQAAxkBAAMWY99USwnPzldN0juJ_oEQE5JnJZAAAh4DAAI3PgxTs9PIJGeFSrwuBA',
  boomKlee: 'CgACAgQAAxkBAAMXY99UZ8sqCePIDvBk7UjmeQ41sFUAAjADAALpZTVTqk4UgCYpnXouBA',
  cryingKlee: 'CgACAgQAAxkBAAMYY99Uaeyjb1qKE1lXurUfdnTKOAwAAiEDAALnXA1TnwFm0tS2KwsuBA'
}
