export const stickers = {
  sadKlee: 'CAACAgIAAxkBAAEcyRBj3nAUiQnfRJj6aUueA6cZ8kYdewACrAsAAqf_QUgcGax9WTL6wC4E',
  kleeAndCat: 'CAACAgIAAxkBAAEcyMZj3mzsN79wou7UdGjr6wQlotqK3AAC4QsAAmmeQEgIPeEJUlAsii4E'
}

export const gifs = {
  attackedKlee: 'CgACAgIAAxkBAAIJIGPfRK5y66tdPZJnLslnSqZYih2-AAISCgACzcdISMioW398Cg8lLgQ',
  jumpingKlee: 'CgACAgIAAxkBAAIJIWPfRMIvf5v-FpIYmVRT19ngNZ5QAAJdHQACISVoSca_waZ2ONFKLgQ',
  waitingKlee: 'CgACAgQAAxkBAAIJImPfRNFrREFAWZWfw4yYWL0V7XnUAAICAwACkU8VU_ZShfAXmFXPLgQ',
  flexingKlee: 'CgACAgIAAxkBAAIJI2PfROTv0hpDFRwXhWQD-JG3UWxEAAJoHAACltDhS2y2rpGgPeAmLgQ',
  diyingOfCringeKlee: 'CgACAgIAAxkBAAIJJGPfRPU_K5aB5EfFpzkQSh8Q4sE9AALVEwAC0u7QSRWGy1YOllPZLgQ',
  helloChatKlee: ' CgACAgQAAxkBAAIJJmPfRT31xYva2wJcXFgaQDtVjEYwAAJnAwAC75TUU1hzQ8JDn3k3LgQ',
  backToBoomKlee: 'CgACAgQAAxkBAAIJJ2PfRU-eDAzhGDVhCwSF5Cb3mdO6AAJlAwACqXGUUpWQAAGOvtGZVi4E',
  seriousKlee: 'CgACAgQAAxkBAAIJKGPfRV9FxR1GY4vvAr3GWLrEE23qAAMDAAJBdQxT_juchiEGhWIuBA',
  agroKlee: 'CgACAgQAAxkBAAIJKWPfRWzilFSQ5K9n_s7cuQNOqLCjAAIeAwACNz4MU7qGNAABWEN6vi4E',
  boomKlee: 'CgACAgQAAxkBAAIJKmPfRYalUOPaFjY91LLCQdWQ57DGAAIwAwAC6WU1U41RbfJ-JnEAAS4E',
  cryingKlee: 'CgACAgQAAxkBAAIJK2PfRZQeJXPzvk51v72PcGoZ0CpHAAIhAwAC51wNU7Tbd75fRY92LgQ'
}
